# wrangler.toml
name = 'empty-boat-23ee'
main = "src/worker.js"
compatibility_date = "2026-04-21"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "apitest_bind"
database_name = "apitest"
database_id = "a6f6157d-9a15-41ee-8c04-68d8dc7d0b9c"
